### ISSUE TITLE
app key?

### ISSUE THREAD

**Issue by emanueldev1** [TheIndra55/discourse-user-api-keys#1]
where do i get the application key?

**Comment by TheIndra55** [comment]
The application key or ID must just be an unique string for your application, you don't have to create it somewhere

**Comment by emanueldev1** [comment]
Thanks, and if I want to do it with node.js, how can I do it? because I don't understand how I can do openssh

**Comment by TheIndra55** [comment]
You can use the crypto module in Node.js, see https://gist.github.com/TheIndra55/0489088590315b102e1b0813fa21b788

**Comment by emanueldev1** [comment]
thanks
